name: Go

on: [push, pull_request]

jobs:

  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.16', '1.17' ]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Test
      run: go test -race -count 2 -bench . ./...

    - name: Bench
      run: go test -run @ -bench . ./...

    - name: Test on 386
      run: GOARCH=386 go test ./... -bench .
      continue-on-error: true

    - name: Some packages compile for WebAssembly
      run: GOOS=js GOARCH=wasm go build . ./storage ./tracker/...

    - name: Install godo
      run: go install github.com/anacrolix/godo@latest

    - name: Apt packages
      run: sudo apt install pv fuse

    - name: torrentfs end-to-end test
      run: fs/test.sh
      timeout-minutes: 10
